name: Reinis Inkēns Photography
favicon: null
layout_spectrum: 0.75196
typography_spectrum: 0.25568
title: Reinis Inkēns Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-74993143-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f8f2ef'
    - '#adc8f3'
    - '#181213'
    - '#ffc400'
    - '#8bab00'
  brandStrength: 0
  lightness: 0.5625
  saturation: 0.875
  rhythmicContrast: 0.75
purpose: []
