name: Reinis Inkēns Photography
favicon: null
layout_spectrum: 0
typography_spectrum: 0.25568
title: Reinis Inkēns Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-74993143-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#002958'
    - '#9a8490'
    - '#7d4447'
  brandStrength: 0
  lightness: 0.5625
  saturation: 0.875
  rhythmicContrast: 0.75
purpose: []
