name: Reinis Inkēns Photography
favicon: null
layout_spectrum: 1
typography_spectrum: 0.3066
title: Reinis Inkēns Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f0ebe7'
    - '#161422'
    - '#810016'
    - '#52445d'
    - '#c4b0b2'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
