name: Reinis Inkēns Photography
favicon: null
layout_spectrum: 1
typography_spectrum: 0.40499
title: Reinis Inkēns Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-74993143-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f0ebe7'
    - '#161422'
    - '#810016'
    - '#52445d'
    - '#c4b0b2'
  brandStrength: 0.125
  lightness: 0.5625
  saturation: 0.875
  rhythmicContrast: 0.5
purpose: []
