name: Reinis Inkēns Photography
favicon: null
layout_spectrum: 0
typography_spectrum: 0.25568
title: Reinis Inkēns Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-74993143-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7c74c3'
    - '#ffe488'
    - '#3f35a7'
    - '#a9a4d9'
    - '#efc532'
  brandStrength: 0.3125
  lightness: 0.625
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
