typography_spectrum: 0.25568
color:
  brandColors:
    - '#7c74c3'
    - '#ffe488'
    - '#3f35a7'
    - '#a9a4d9'
    - '#efc532'
  brandStrength: 0.25
  lightness: 0.6875
  saturation: 0.875
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0
analytics:
  google: UA-74993143-1
  facebook: null
  twitter: null
name: Reinis Inkēns Photography
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Par mani
    id: 61f19d6f-b517-4cc5-a68e-5c896002aea6
    type: content
  - name: Mani video darbi
    url: dicethrowfilms.eu
    type: external
favicon: null
title: Reinis Inkēns Photography
purpose: []
